# The newest TRMT: Reimagined build for each edition, and for each edition at each stage
# (<edition>.<stage>). Written by export_release.py; read once per launch by every released
# jar. Never move this file.
1.7.10-forge=0.9.220
1.7.10-forge.alpha=0.9.220
1.7.10-forge.beta=0.9.220
1.7.10-forge.nightly=0.9.220
1.12.2-forge=0.9.220
1.12.2-forge.alpha=0.9.220
1.12.2-forge.beta=0.9.220
1.12.2-forge.nightly=0.9.220
1.16.5-forge=0.9.220
1.16.5-forge.alpha=0.9.220
1.16.5-forge.beta=0.9.220
1.16.5-forge.nightly=0.9.220
1.16.5-fabric=0.9.220
1.16.5-fabric.alpha=0.9.220
1.16.5-fabric.beta=0.9.220
1.16.5-fabric.nightly=0.9.220
