# The newest TRMT: Reimagined build for each edition, and for each edition at each stage
# (<edition>.<stage>); with .relevant, the newest that changed that jar, and .critical the newest
# critical for it. Written by the release tools; read once per launch by every released jar.
# Never move this file.
1.7.10-forge=0.9.221
1.7.10-forge.relevant=0.9.221
1.7.10-forge.alpha=0.9.221
1.7.10-forge.alpha.relevant=0.9.221
1.7.10-forge.beta=0.9.221
1.7.10-forge.beta.relevant=0.9.221
1.7.10-forge.nightly=0.9.221
1.7.10-forge.nightly.relevant=0.9.221
1.12.2-forge=0.9.221
1.12.2-forge.relevant=0.9.221
1.12.2-forge.alpha=0.9.221
1.12.2-forge.alpha.relevant=0.9.221
1.12.2-forge.beta=0.9.221
1.12.2-forge.beta.relevant=0.9.221
1.12.2-forge.nightly=0.9.221
1.12.2-forge.nightly.relevant=0.9.221
1.16.5-forge=0.9.221
1.16.5-forge.relevant=0.9.221
1.16.5-forge.alpha=0.9.221
1.16.5-forge.alpha.relevant=0.9.221
1.16.5-forge.beta=0.9.221
1.16.5-forge.beta.relevant=0.9.221
1.16.5-forge.nightly=0.9.221
1.16.5-forge.nightly.relevant=0.9.221
1.16.5-fabric=0.9.221
1.16.5-fabric.relevant=0.9.221
1.16.5-fabric.alpha=0.9.221
1.16.5-fabric.alpha.relevant=0.9.221
1.16.5-fabric.beta=0.9.221
1.16.5-fabric.beta.relevant=0.9.221
1.16.5-fabric.nightly=0.9.221
1.16.5-fabric.nightly.relevant=0.9.221
says.0.9.221=Smarter update notices, crash help links
requires.1.12.2-forge.mixinbooter.minimum=8.0
requires.1.12.2-forge.mixinbooter.recommended=11.13
requires.1.16.5-fabric.cloth-config2.minimum=4.14.54
requires.1.16.5-fabric.cloth-config2.recommended=4.17.132
requires.1.16.5-fabric.fabric.minimum=0.29.4+1.16
requires.1.16.5-fabric.fabric.recommended=0.42.0+1.16
requires.1.16.5-forge.cloth-config.minimum=4.11.26
requires.1.16.5-forge.cloth-config.recommended=4.17.132
requires.1.7.10-forge.unimixins.minimum=0.1.11
requires.1.7.10-forge.unimixins.recommended=0.1.23
